[package]
name = "cawr-application"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# Workspace dependencies
cawr-domain = "0.0.0"

# External dependencies
log = "*"
thiserror = "1"
