[package]
name = "clean-architecture-with-rust"
version = "0.0.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2018"
publish = false

[workspace]
members = [
  "adapter",
  "adapter/json-boundary",
  "application",
  "domain",
  "infrastructure"
]
exclude = [ "webapp" ]

[dependencies]
infrastructure = "0.0.0"

[patch.crates-io]
adapter = { path = "adapter" }
application = { path = "application" }
domain = { path = "domain" }
infrastructure = { path = "infrastructure" }
json-boundary = { path = "adapter/json-boundary" }
