[package]
name = "clean-architecture-with-rust"
version = "0.0.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2021"
publish = false

[workspace]
members = [
  "adapter",
  "adapter/json-boundary",
  "application",
  "domain",
  "infrastructure",
  "infrastructure/db",
  "infrastructure/web-server"
]
exclude = [ "webapp" ]

[dependencies]
infrastructure = "0.0.0"

[patch.crates-io]
adapter        = { path = "adapter"                   }
application    = { path = "application"               }
db             = { path = "infrastructure/db"         }
domain         = { path = "domain"                    }
infrastructure = { path = "infrastructure"            }
json-boundary  = { path = "adapter/json-boundary"     }
web-server     = { path = "infrastructure/web-server" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = true
