[package]
name = "cawr-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
cawr-adapter = "=0.0.0"

# External dependencies
clap = { version = "4.5", features = ["derive"] }
