[package]
name = "cawr-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
# Workspace dependencies
cawr-adapter = "0.0.0"

# External dependencies
clap = { version = "4", features = ["derive"] }
