[package]
name = "cawr-json-boundary"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde = { version = "1.0", features =  ["derive"] }
