[package]
name = "cawr-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
cawr-domain = "=0.0.0"

# External dependencies
log = "0.4"
parking_lot = "0.12"
thiserror = "1.0"
