[package]
name = "infrastructure"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]

# Workspace dependencies
adapter = "0.0.0"
application = "0.0.0"
domain = "0.0.0"
entity = "0.0.0"

# External dependencies
pretty_env_logger = "*"
log = "*"
jfs = "*"
serde = { version = "1", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["full"] }
warp = "*"

[dev-dependencies]
anyhow = "*"
hyper = "*"
serde_json = "1"
