[package]
name = "infrastructure"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]

# Workspace dependencies
adapter = "*"
application = "*"
domain = "*"
entity = "*"

# External dependencies
jfs = "*"
serde = { version = "1", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
