[package]
name = "adapter"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
# Workspace dependencies
application = "0.0.0"
domain = "0.0.0"

# External dependencies
http = "*"
http-serde = "*"
log = "*"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
