[package]
name = "webapp"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
json-boundary = "*"
seed = "*"
serde = "1"

[patch.crates-io]
json-boundary = { path = "../adapter/json-boundary" }
