name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Install trunk
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.13.1/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -C ~/.cargo/bin -xzf-

      - name: Build webapp
        run: |
          cd webapp/
          rustup target add wasm32-unknown-unknown
          trunk -V
          trunk build

      - name: Check code formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check for linter warnings
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Test project
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-features

      - name: Check code coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: --ignore-tests --workspace
